### PR TITLE
Jensbranch

### PR DESCRIPTION
**Pull request by JenniferLang1921**

### CODE REVIEW

**Comment by JenniferLang1921** [comment]
I'm mainly just pulling all the changes and getting my files up to date, there shouldn't be many changes on my end.

**Review by SuiteMel — CHANGES_REQUESTED** [review]
Looks like you didn’t fix a conflict in PlantCard.js. Fix that and you should be good to go.

**Comment by JenniferLang1921** [comment]
okay, I fixed it.  Thanks!

**Review by green64 — APPROVED** [review]

**Review by green64 — APPROVED** [review]

**Review by SuiteMel — APPROVED** [review]
Looks good.

**Pull request merged**
